language: node_js
sudo: true
node_js:
- '9'

install:
- ./scripts/bootstrap.sh

script:
- yarn lint
- yarn test

after_success:
- ./scripts/travis-publish-test.sh

notifications:
  email: false
  webhooks: https://www.travisbuddy.com
  on_success: never