language: node_js
sudo: true
node_js:
- '8'

before_install:
- npm install exp --global

install:
- make install

script:
- make lint
- make test

after_success:
- make test-deploy
- make production-deploy

notifications:
  email: false
  webhooks: https://www.travisbuddy.com

